package agent

import (
    "fmt"
    "time"
)

// GenerateDemoPlan creates a sample plan for demo/testing purposes
func GenerateDemoPlan(userName string, weekStart time.Time) string {
    weekEnd := weekStart.AddDate(0, 0, 6)

    plan := fmt.Sprintf(`WEEKLY TRAINING PLAN
Week of: %s - %s

⚠️  DEMO MODE: This is a sample plan generated without AI.
    Set ANTHROPIC_API_KEY to get personalized AI-generated plans.

RATIONALE:
This demo week focuses on building a balanced training foundation combining technical skills, conditioning, and strength work. The plan includes a mix of boxing-specific training and supplementary conditioning to develop well-rounded fitness. Recovery is prioritized with strategic rest days to prevent overtraining.

WEEKLY OVERVIEW:
- 5 training sessions across the week
- 2 full rest days for recovery
- Mix of technical work, conditioning, and strength training
- Progressive intensity throughout the week

DAILY BREAKDOWN:

Monday:
  Session: Technical Drilling & Bag Work
  Duration: 60 minutes
  Focus: Fundamental boxing techniques and combinations
  Details:
    - Warmup: 10 min jump rope and dynamic stretching
    - Shadow boxing: 3 rounds focusing on stance, footwork, basic combinations
    - Heavy bag: 6 rounds (3 min each) - jab, cross, hook combinations
    - Speed bag: 3 rounds for hand-eye coordination
    - Cooldown: stretching
  Why: Starting the week with technical work when fresh helps reinforce proper form

Tuesday:
  Session: Strength Training
  Duration: 75 minutes
  Focus: Full body strength with emphasis on functional movements
  Details:
    - Warmup: 10 min cardio
    - Compound lifts: Deadlifts 4x5, Overhead Press 4x8, Squats 3x8
    - Accessory: Pull-ups 3x8, Dips 3x10, Core work 10 min
    - Cooldown: mobility work
  Why: Building strength foundation that transfers to boxing power

Wednesday:
  Session: REST DAY
  Duration: -
  Focus: Recovery and regeneration
  Details: Light stretching, walking, or complete rest. Stay hydrated and focus on nutrition.
  Why: Mid-week recovery allows the body to adapt to training stress

Thursday:
  Session: Conditioning & Cardio
  Duration: 45 minutes
  Focus: Aerobic capacity and work capacity
  Details:
    - Warmup: 5 min dynamic movement
    - Roadwork: 30 min steady-state run at conversational pace
    - Intervals: 5x1 min hard, 1 min recovery
    - Cooldown: 5 min walk and stretch
  Why: Building the aerobic base needed for sustained effort in boxing

Friday:
  Session: Padwork & Sparring Prep
  Duration: 60 minutes
  Focus: Combinations, timing, and defensive movements
  Details:
    - Warmup: shadow boxing 2 rounds
    - Focus mitt work with partner: 6 rounds working various combinations
    - Defensive drills: slipping, rolling, blocking practice
    - Light bag work: 2 rounds
    - Cooldown and stretch
  Why: Padwork develops timing, accuracy, and live feedback from a partner

Saturday:
  Session: Active Recovery
  Duration: 30 minutes
  Focus: Light movement and mobility
  Details:
    - Light shadow boxing: 2 rounds at 50%% intensity
    - Yoga or stretching routine: 20 minutes
    - Foam rolling: target any tight areas
  Why: Active recovery promotes blood flow and aids recovery without adding fatigue

Sunday:
  Session: REST DAY
  Duration: -
  Focus: Complete rest and preparation for next week
  Details: Meal prep, review the week's training, set intentions for next week.
  Why: Full recovery before starting a new training week

NOTES:
- Listen to your body - if overly fatigued, take an additional rest day
- Stay hydrated throughout the week (aim for clear/pale urine)
- Prioritize sleep (7-9 hours per night)
- Nutrition: focus on whole foods, adequate protein (1.6-2g per kg bodyweight)
- Flexibility: sessions can be moved if schedule conflicts arise, but maintain the overall balance

NEXT WEEK PREVIEW:
Next week we'll increase intensity slightly, potentially adding sparring if you're ready. Continue building on this foundation with progressive overload in strength training and increased volume in boxing work.

═══════════════════════════════════════════════════════════
Generated by IamFeel (Demo Mode)
For personalized AI plans, set your ANTHROPIC_API_KEY
═══════════════════════════════════════════════════════════`,
        weekStart.Format("Jan 2"),
        weekEnd.Format("Jan 2, 2006"),
    )

    return plan
}
